root := justfile_directory()

export TYPST_ROOT := root

set allow-duplicate-recipes := true

set positional-arguments := true


# @ ----------------
# @ DEFAULT
# @ ----------------

[private]
@default:
  just -l

[group('Cleaning')]
[private]
rm:
    rm -rf ./dist/*
    touch ./dist/.gitkeep

[group('Build')]
kaomoji: rm
    typst compile --pages 1 kaomoji.typ ./dist/kaomoji-1.png
    typst compile --pages 2 kaomoji.typ ./dist/kaomoji-2.png
    typst compile --pages 3 kaomoji.typ ./dist/kaomoji-3.png

